// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_KwUG13yRNjQHVoNdCnsRwWjYcXg3zTg',
    appId: '1:250009185281:web:86a6c376beb991c1166400',
    messagingSenderId: '250009185281',
    projectId: 'innovative-minds-62e50',
    authDomain: 'innovative-minds-62e50.firebaseapp.com',
    storageBucket: 'innovative-minds-62e50.appspot.com',
    measurementId: 'G-NQP68WC6KD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3AmUq5MhAZwy80N9VFUwh1Ty5KFzVmEQ',
    appId: '1:250009185281:android:3a956aaaea312a2b166400',
    messagingSenderId: '250009185281',
    projectId: 'innovative-minds-62e50',
    storageBucket: 'innovative-minds-62e50.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhQt54veB1xL3xGeJVIug7pM0f4kWXtQ0',
    appId: '1:250009185281:ios:3a411c848649ab95166400',
    messagingSenderId: '250009185281',
    projectId: 'innovative-minds-62e50',
    storageBucket: 'innovative-minds-62e50.appspot.com',
    iosClientId: '250009185281-udv9lmn2l2oqqqbsv6drnngpcrtlchjl.apps.googleusercontent.com',
    iosBundleId: 'com.example.connectify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhQt54veB1xL3xGeJVIug7pM0f4kWXtQ0',
    appId: '1:250009185281:ios:3a411c848649ab95166400',
    messagingSenderId: '250009185281',
    projectId: 'innovative-minds-62e50',
    storageBucket: 'innovative-minds-62e50.appspot.com',
    iosClientId: '250009185281-udv9lmn2l2oqqqbsv6drnngpcrtlchjl.apps.googleusercontent.com',
    iosBundleId: 'com.example.connectify',
  );
}
